language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -q errbot pytest pytest-pep8 --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source funbot -m py.test
after_success:
  - coveralls
notifications:
  email: false
